### ISSUE TITLE
Ignore case in filename

### ISSUE THREAD

**Issue by anbj** [akirmse/mountains#34]
Not a big problem, but still.

If your file is named ``N59E005.HGT``, prominence will not recognize the file and not run.
Change the name to ``N59E005.hgt`` and it'll run fine.

What about ignoring case in filename and/or file extension?

**Comment by akirmse** [comment]
In order to do this, the program would need to load the entire directory listing to do a case-insensitive comparison.  This could be a performance problem, as I sometimes run on directories with tens of thousands of tiles on a slow external drive.  

It also strikes me as a somewhat dangerous feature.  If you have both N59E005.HGT and N59E005.hgt in the same directory, you'd get one at random.

**Comment by anbj** [comment]
Valid points. Closing.
